version: "3.9"
services:
  mmdvm_hs:
    container_name: mmdvm_hs
    platform: linux/arm/v7
    build:
      context: .
      dockerfile: Dockerfile
      platforms: 
        - linux/arm/v7
      args:
        # TYPEs supported:
        #  D2RG_MMDVM_HS generic_gpio MMDVM_HS_Dual_Hat
        #  NanoDV_NPI SkyBridge_RPi ZUMspot_Libre generic_duplex_gpio
        #  LoneStar_USB MMDVM_HS_Hat-12mhz NanoDV_USB ZUMspot_dualband
        #  ZUMspot_RPi generic_duplex_usb MMDVM_HS_Dual_Hat-12mhz
        #  MMDVM_HS_Hat Nano_hotSPOT ZUMspot_duplex ZUMspot_USB
        TYPE: MMDVM_HS_Hat
    volumes:
      - ./:/artifacts
    network_mode: none
    restart: no