version: "3.9"
services:
  mmdvm_hs:
    container_name: mmdvm_hs
    user: 501:20
    platform: linux/arm/v7
    build:
      context: .
      dockerfile: Dockerfile
      platforms: 
        - linux/arm/v7
      args:
        TYPE: generic_gpio
    volumes:
      - ./:/artifacts
    network_mode: none
    restart: no
